### ISSUE TITLE
Task 01-Filters

### ISSUE THREAD

**Issue by caroortegaa** [Tornierm/HCI-Project#3]
Elaborate a screen for the filters following the design from the screen from the second prototype. Implement after the user click on "Filters" on the main screen. Do not forget to specify somehow which are mandatory in order to apply.
[3.pdf](https://github.com/Tornierm/HCI-Project/files/15041901/3.pdf)

**Comment by Tornierm** [comment]
Filters to implement: 

1. Distance
3. Features
4. Restrictions
5. Price
6. Reviews (1/5 ... 5/5)

(I say we move the time frame specification to the booking process only)

Go to Component/Home/Filters.tsx
Click cmd + F
search "to-do"
read instructions
